wageservice:
  datasource:
    wages:
      url: jdbc:postgresql://localhost:5432/hr?currentSchema=wages
      username: postgres
      password: postgres
  liquibase:
    wages:
      change-log: classpath:/changelog/master.xml

management:
  endpoint:
    health:
      enabled: true
      show-components: always
      show-details: always
      cache:
        time-to-live: 10s
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, loggers, metrics, caches

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: debug

server:
  port: 8080
