wageservice:
  datasource:
    wages:
      url: jdbc:postgresql://localhost:5432/hr?currentSchema=wages
      username: postgres
      password: postgres
  liquibase:
    wages:
      change-log: classpath:/changelog/master.xml
  scheduling:
    scheduledAvailabilityUpdates:
      milliseconds: 5000

spring:
  application:
    name: wageservice
#  boot:
#    admin:
#      client:
#        url: http://localhost:8082

management:
  endpoint:
    health:
      enabled: true
      show-components: always
      show-details: always
      cache:
        time-to-live: 10s
      probes:
        enabled: true
      group:
        command.include: personService, wageDataSource
        query.include: wageDataSource
  #  health.db.enabled: false
  endpoints:
    web:
      exposure:
#        include: '*'
        include: health, loggers, metrics, caches

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
#    reactor.netty.http.client.HttpClientConnect: debug
    com.example.wageservice.health.PersonServiceHealthIndicator: trace
    com.example.wageservice.health.WageDataSourceHealthIndicator: trace

server:
  port: 8080
  servlet:
    contextPath: /${spring.application.name}

integration:
  personservice:
    base-url: http://127.0.0.1:8081/personservice
