GET http://localhost:8080/wageservice/actuator/loggers

###

GET http://localhost:8080/wageservice/actuator/loggers/org.springframework.jdbc.core

###

POST http://localhost:8080/wageservice/actuator/loggers/org.springframework.jdbc.core
content-type: application/json

{
  "configuredLevel": "DEBUG"
}

###
